### ISSUE TITLE
Html surround comments

### ISSUE THREAD

**Issue by CristhianMotoche** [manasthakur/vim-commentor#1]
For almost all the comments the application only adds comments at the beggining. This is a problem in Html tags, because it only adds a comment at the beggining of the line.

You can see an example here:
```
<!-- <div> Apply comment only in this line
           This line is not affected, but is inside the tag.
     </div>
```

**Comment by manasthakur** [comment]
Right. I am aware of this.
Basically, I am trimming the `commentstring` to just get the LHS. I will see if I can get the RHS as well in a simplistic manner, over the weekend.

Keep watching :)

**Comment by manasthakur** [comment]
Hi @CristhianMotoche,

Out of interest, I have solved your issue today itself.
Thanks for bringing it up.

_p.s._ As mentioned in the doc, putting the end marker after multiple lines won't be supported. Thus, for the code example given by you, the commented result should look like the following:

```
<!-- <div> Apply comment only in this line-->
<!--           This line is not affected, but is inside the tag.-->
<!--     </div>-->
```

Uncomment also works as before.

**Comment by CristhianMotoche** [comment]
Cool. Thanks @manasthakur
